[package]
name = "kparser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
httlib-huffman = "0.3.4"
# bitflags = "2.6.0"
